# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
weight = 10
url = "https://github.com/hirumeri"

[social.params]
icon = "brand-github"

[[social]]
identifier = "x"
name = "x"
url = "https://twitter.com/hirumeri"
weight = 80

[social.params]
icon = "brand-x"

[[social]]
identifier = "fediverse"
name = "fedibird"
url = ""
weight = 20

[social.params]
icon = "brand-mastodon"

[[social]]
identifier = "rss"
name = "rss"
url = "/post/index.xml"
weight = 100

[social.params]
icon = "rss"