# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/hirumeri"

[social.params]
icon = "brand-github"

[[social]]
identifier = "x"
name = "x"
url = "https://twitter.com/hirumeri"

[social.params]
icon = "brand-x"

[[social]]
identifier = "fediverse"
name = "fedibird"
url = ""

[social.params]
icon = "brand-mastodon"